name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.6.1
homepage: https://github.com/mwaylabs/flutter-apns

plugin:
  platforms:
    android:
      pluginClass: FirebasePushConnector
    ios:
      pluginClass: ApnsPushConnector

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_apns_only: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
